language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

branches:
  only:
  - master
  - dev

addons:
  chrome: stable

script:
  - ng lint
  - ng test --watch false -cc
  - npm run build
  - xvfb-run npm run e2e