apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: omicsdi-prod
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    service.alpha.kubernetes.io/external-traffic: OnlyLocal
spec:
  rules:
  - host: stage.omicsdi.org
    http:
      paths:    
        - backend:
            serviceName: omicsdi-frontend
            servicePort: 8080
      